### ISSUE TITLE
the vesion is confuse

### ISSUE THREAD

**Issue by PHD-jlh** [georgeliu233/STrajNet#5]
Thanks to the author for disclosing the code. 
When I run data_preprocessing.py, tensorflow.python.framework.errors_impl.InvalidArgumentError: Key: roadgraph_samples/xyz appears. I want to know if the version of the data set I downloaded does not correspond to the version of WOD? The dataset version I downloaded is v1.2

**Comment by georgeliu233** [comment]
Hi, sorry for the late reply!

The code is developed upon previous v1.0, so some keys related to roadgraph has been modified or added (just 1-2 keys I think), so you may follow the current key annotations and change accordingly 

Best :)
